# 1. Data loading

In [21]:
import pandas as pd
df = pd.read_csv("../data/raw/firms_wildfire.txt")
df.head(3)

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight
0,-5.07064,-37.71648,305.08,0.42,0.37,2026-04-24,408,N,VIIRS,n,2.0NRT,291.07,0.71,N
1,-4.36557,-37.89799,311.47,0.41,0.37,2026-04-24,408,N,VIIRS,n,2.0NRT,292.18,2.70,N
2,-4.36499,-37.90164,333.37,0.41,0.37,2026-04-24,408,N,VIIRS,n,2.0NRT,292.52,2.70,N

# 2. Data cleaning

In [22]:
import geopandas as gpd
wildfire_gdf=gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df["longitude"], df["latitude"]), crs=(4326))
wildfire_gdf.head(3)

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight,geometry
0,-5.07064,-37.71648,305.08,0.42,0.37,2026-04-24,408,N,VIIRS,n,2.0NRT,291.07,0.71,N,POINT (-37.71648 -5.07064)
1,-4.36557,-37.89799,311.47,0.41,0.37,2026-04-24,408,N,VIIRS,n,2.0NRT,292.18,2.70,N,POINT (-37.89799 -4.36557)
2,-4.36499,-37.90164,333.37,0.41,0.37,2026-04-24,408,N,VIIRS,n,2.0NRT,292.52,2.70,N,POINT (-37.90164 -4.36499)

# 3. Spatial analysis

In [ ]:
#Code

# 4. Visualization

In [ ]:
import folium
from folium.plugins import MarkerCluster

# Create a new Folium map object.
m = folium.Map()
folium.GeoJson(wildfire_gdf).add_to(m) 
m

In [8]:
wildfire_points=folium.GeoJson(wildfire_gdf)
cluster = MarkerCluster(name="wildfire_points").add_to(map)
display(cluster)

AttributeError: type object 'map' has no attribute 'add_child'